name: ControlCore Auto AI Reviewer

on:
  pull_request:
    # Triggers on PR creation, new commits (synchronize), or reopening
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  gemini-code-review:
    runs-on: ubuntu-latest
    # This ensures the action only runs on your specific repository
    if: github.repository == 'GREENRAT-K405/playground' # Update this to your repo path
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gemini AI Review
        uses: truongnh1992/gemini-ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-2.0-flash
          # Focused exclusions for a control systems project
          EXCLUDE: "*.md, *.txt, *.json, *.yml, *.yaml, .gitignore, LICENSE, docs/**"